artifact_uri: file:///C:\Users\Ares\Documents\LIBROS\PLATZI CURSOS\CIENCIA DE DATOS\MACHINE
  LEARNING\laboratorio-machine-learning\ml_experiments/406633100773434584/a3ade556f31c4173b59fb0548d27b2d1/artifacts
end_time: 1743200695247
entry_point_name: ''
experiment_id: '406633100773434584'
lifecycle_stage: active
run_id: a3ade556f31c4173b59fb0548d27b2d1
run_name: extra_trees_normal
run_uuid: a3ade556f31c4173b59fb0548d27b2d1
source_name: ''
source_type: 4
source_version: ''
start_time: 1743200670988
status: 3
tags: []
user_id: Ares
