artifact_location: file:///C:\Users\Ares\Documents\LIBROS\PLATZI CURSOS\CIENCIA DE
  DATOS\MACHINE LEARNING\laboratorio-machine-learning\ml_experiments/406633100773434584
creation_time: 1742998725059
experiment_id: '406633100773434584'
last_update_time: 1742998725059
lifecycle_stage: active
name: churn_ml
