artifact_uri: file:///C:\Users\Ares\Documents\LIBROS\PLATZI CURSOS\CIENCIA DE DATOS\MACHINE
  LEARNING\laboratorio-machine-learning\ml_experiments/406633100773434584/a2cee86b87f941eeb6151bca7e299f41/artifacts
deleted_time: 1743132906597
end_time: 1743132378334
entry_point_name: ''
experiment_id: '406633100773434584'
lifecycle_stage: deleted
run_id: a2cee86b87f941eeb6151bca7e299f41
run_name: rf_1
run_uuid: a2cee86b87f941eeb6151bca7e299f41
source_name: ''
source_type: 4
source_version: ''
start_time: 1743132366810
status: 3
tags: []
user_id: Ares
