artifact_uri: file:///C:\Users\Ares\Documents\LIBROS\PLATZI CURSOS\CIENCIA DE DATOS\MACHINE
  LEARNING\laboratorio-machine-learning\ml_experiments/406633100773434584/5acaed0f8d3e4ad7b9d7a7a9c518899d/artifacts
deleted_time: 1743174293437
end_time: 1743133576584
entry_point_name: ''
experiment_id: '406633100773434584'
lifecycle_stage: deleted
run_id: 5acaed0f8d3e4ad7b9d7a7a9c518899d
run_name: rf_smoteenn
run_uuid: 5acaed0f8d3e4ad7b9d7a7a9c518899d
source_name: ''
source_type: 4
source_version: ''
start_time: 1743133441955
status: 3
tags: []
user_id: Ares
