artifact_location: file:///C:\Users\Ares\Documents\LIBROS\PLATZI CURSOS\CIENCIA DE
  DATOS\MACHINE LEARNING\laboratorio-machine-learning\ml_experiments/0
creation_time: 1742998725042
experiment_id: '0'
last_update_time: 1742998725042
lifecycle_stage: active
name: Default
