channels:
- conda-forge
dependencies:
- python=3.12.9
- pip<=25.0.1
- pip:
  - mlflow==2.20.2
  - cloudpickle==3.0.0
  - numpy==1.26.1
  - psutil==6.1.1
  - scikit-learn==1.3.2
  - scipy==1.11.3
name: mlflow-env
