artifact_uri: file:///C:\Users\Ares\Documents\LIBROS\PLATZI CURSOS\CIENCIA DE DATOS\MACHINE
  LEARNING\laboratorio-machine-learning\ml_experiments/406633100773434584/c526123d4919405bb861e7e1dd3f48b3/artifacts
end_time: 1743199976882
entry_point_name: ''
experiment_id: '406633100773434584'
lifecycle_stage: active
run_id: c526123d4919405bb861e7e1dd3f48b3
run_name: xgb_smoteenn
run_uuid: c526123d4919405bb861e7e1dd3f48b3
source_name: ''
source_type: 4
source_version: ''
start_time: 1743199934744
status: 3
tags: []
user_id: Ares
