artifact_uri: file:///C:\Users\Ares\Documents\LIBROS\PLATZI CURSOS\CIENCIA DE DATOS\MACHINE
  LEARNING\laboratorio-machine-learning\ml_experiments/406633100773434584/0a8fe7a28e3f4ae996e514c00f9afa36/artifacts
end_time: 1743000483214
entry_point_name: ''
experiment_id: '406633100773434584'
lifecycle_stage: active
run_id: 0a8fe7a28e3f4ae996e514c00f9afa36
run_name: propotipe_1
run_uuid: 0a8fe7a28e3f4ae996e514c00f9afa36
source_name: ''
source_type: 4
source_version: ''
start_time: 1743000474377
status: 3
tags: []
user_id: Ares
