artifact_uri: file:///C:\Users\Ares\Documents\LIBROS\PLATZI CURSOS\CIENCIA DE DATOS\MACHINE
  LEARNING\laboratorio-machine-learning\ml_experiments/406633100773434584/8d016b155b9f4ec6b7ce0447d5ee5136/artifacts
end_time: 1742998725894
entry_point_name: ''
experiment_id: '406633100773434584'
lifecycle_stage: active
run_id: 8d016b155b9f4ec6b7ce0447d5ee5136
run_name: propotipe_1
run_uuid: 8d016b155b9f4ec6b7ce0447d5ee5136
source_name: ''
source_type: 4
source_version: ''
start_time: 1742998725851
status: 3
tags: []
user_id: Ares
