artifact_uri: file:///C:\Users\Ares\Documents\LIBROS\PLATZI CURSOS\CIENCIA DE DATOS\MACHINE
  LEARNING\laboratorio-machine-learning\ml_experiments/406633100773434584/600ff6f697864f85a55dedb194ada803/artifacts
end_time: 1743185165842
entry_point_name: ''
experiment_id: '406633100773434584'
lifecycle_stage: active
run_id: 600ff6f697864f85a55dedb194ada803
run_name: xgb_smoteenn
run_uuid: 600ff6f697864f85a55dedb194ada803
source_name: ''
source_type: 4
source_version: ''
start_time: 1743185153591
status: 3
tags: []
user_id: Ares
