artifact_uri: file:///C:\Users\Ares\Documents\LIBROS\PLATZI CURSOS\CIENCIA DE DATOS\MACHINE
  LEARNING\laboratorio-machine-learning\ml_experiments/406633100773434584/3ef67564a05e4947bfeda9b31f285536/artifacts
end_time: 1743182570158
entry_point_name: ''
experiment_id: '406633100773434584'
lifecycle_stage: active
run_id: 3ef67564a05e4947bfeda9b31f285536
run_name: rf_smoteenn
run_uuid: 3ef67564a05e4947bfeda9b31f285536
source_name: ''
source_type: 4
source_version: ''
start_time: 1743182298688
status: 3
tags: []
user_id: Ares
