artifact_uri: file:///C:\Users\Ares\Documents\LIBROS\PLATZI CURSOS\CIENCIA DE DATOS\MACHINE
  LEARNING\laboratorio-machine-learning\ml_experiments/406633100773434584/c556f09a5db44cee88c63c45d20b3ef7/artifacts
end_time: 1743200322362
entry_point_name: ''
experiment_id: '406633100773434584'
lifecycle_stage: active
run_id: c556f09a5db44cee88c63c45d20b3ef7
run_name: xgb_smoteenn
run_uuid: c556f09a5db44cee88c63c45d20b3ef7
source_name: ''
source_type: 4
source_version: ''
start_time: 1743200251846
status: 3
tags: []
user_id: Ares
